title: 周子栋 | Personal Homepage
page-top-title: 周子栋
top-section-bg-text: Be what you wanna be
home-subtitle: 周子栋 &ensp;|&ensp; 控制工程硕士在读
copyright-text: Copyright © 周子栋
github-link: GitHub
license-link: Template License
